# Generated by Django 4.0.6 on 2022-10-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=120)),
                ('mandarin', models.CharField(max_length=40)),
                ('completed', models.BooleanField(default=False)),
                ('revised', models.IntegerField(default=0)),
                ('added', models.DateTimeField(default=None)),
            ],
        ),
    ]
