# Generated by Django 4.0.6 on 2022-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='definition',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='words',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='words',
            name='english',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='words',
            name='mandarin',
            field=models.CharField(default='', max_length=40),
        ),
    ]
