# Generated by Django 4.0.6 on 2022-10-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_words_definition_words_type_alter_words_english_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
