# Generated by Django 4.0.6 on 2022-10-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_rename_words_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='type',
            new_name='grammatical_type',
        ),
        migrations.AddField(
            model_name='word',
            name='pinyin',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='word',
            name='used_in_a_sentence',
            field=models.CharField(default='', max_length=240),
        ),
    ]
