# Generated by Django 3.0.1 on 2022-10-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20221026_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='arabic',
            field=models.CharField(default='', max_length=40),
        ),
    ]
