import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/Navbar/NavBar'
import Footer from '../components/Footer/Footer'
import Playground from '../components/Playground/Playground'


export default function Home(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Voc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
          <Playground word={props.word}/>
      </main>
      <Footer />
    </div>
  )
}
