import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import Playground from '../components/Playground/Playground'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Voc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <NavBar />
          
          <Playground />
          <Footer />
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
